# Continuous integration for Windows using http://appveyor.com/

# Not a .NET project, we build ci-helpers in the install step instead
build: false

# Only build pushes to the master branch.
branches:
    only:
        - master

environment:
    matrix:
        - PYTHON: "C:\\Python27"
          PYTHON_VERSION: "2.7"
          PYTHON_ARCH: "32"
          MINICONDA: C:\Miniconda

        - PYTHON: "C:\\Python27"
          PYTHON_VERSION: "2.7"
          PYTHON_ARCH: "64"
          MINICONDA: C:\Miniconda-x64

        #- PYTHON: "C:\\Python35"
          #PYTHON_VERSION: "3.5"
          #PYTHON_ARCH: "32"
          #MINICONDA: C:\Miniconda35
            #
        #- PYTHON: "C:\\Python35"
          #PYTHON_VERSION: "3.5"
          #PYTHON_ARCH: "64"
          #MINICONDA: C:\Miniconda35-x64

init:
    - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

install:
    - cmd: set "PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
    - cmd: conda config --set always_yes yes --set changeps1 no
    - cmd: conda update -q conda
    - cmd: conda info -a
    - cmd: conda create -q -n testenv python="%PYTHON_VERSION%"
    - cmd: activate testenv
    - cmd: conda install --file "ci\\requirements-conda.txt"
    - cmd: python setup.py sdist --formats=zip
    - ps: ls dist
    - ps: pip install --no-deps (Get-ChildItem dist\fatiando-*.zip)


test_script:
    - ps: mkdir -p tmp; cd tmp; python -c "import fatiando; print('Installed:', fatiando.__file__, 'and', fatiando.__version__); fatiando.test(verbose=True)"
